# angular-app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-frontend
  template:
    metadata:
      labels:
        app: devops-frontend
    spec:
      containers:
        - name: devops-frontend-container
          image: saltytoona/devopsfrontend:latest
          ports:
            - containerPort: 4200
