name: On Merge in Main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  es-lint-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Check linting rules
        run: npm run lint
